# Generated by Django 2.1 on 2018-09-04 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('label', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ControlFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorecard.BusinessUnit')),
            ],
        ),
        migrations.CreateModel(
            name='ProductControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorecard.Control')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorecard.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='control',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorecard.ControlFamily'),
        ),
        migrations.AddField(
            model_name='control',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorecard.Standard'),
        ),
    ]
