# Generated by Django 2.1 on 2018-09-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0002_auto_20180904_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_score',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
