# Generated by Django 2.1 on 2018-09-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0003_auto_20180925_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='percent_score',
            field=models.FloatField(default=0),
        ),
    ]
