# Generated by Django 2.1 on 2018-09-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0005_securitycapability_securitycapabilityproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitycapability',
            name='supporting_controls',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='securitycapability',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='securitycapabilityproduct',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
