# Generated by Django 2.1 on 2018-09-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0006_auto_20180927_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='securitycapability',
            name='supporting_controls',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='securitycapabilityproduct',
            name='status',
            field=models.ForeignKey(blank=True, on_delete=models.SET(''), to='scorecard.Status'),
        ),
    ]
