# Generated by Django 2.1 on 2018-09-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0007_auto_20180927_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='status',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
