# Generated by Django 2.1.2 on 2018-10-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0009_auto_20180927_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='business_unit',
            field=models.ForeignKey(null=True, on_delete=models.SET(None), to='scorecard.BusinessUnit'),
        ),
    ]
