# Generated by Django 2.1.2 on 2018-10-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0011_auto_20181005_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessunit',
            name='pp_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='businessunitgroup',
            name='pp_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='pp_id',
            field=models.IntegerField(default=0),
        ),
    ]
