# Generated by Django 2.1.2 on 2018-10-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0013_person_productrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
