# Generated by Django 2.1.2 on 2018-10-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0014_person_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitycapabilityproduct',
            name='status',
            field=models.ForeignKey(null=True, on_delete=models.SET(''), to='scorecard.Status'),
        ),
    ]
