# Generated by Django 2.1.2 on 2018-10-10 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0015_auto_20181010_1437'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SecurityCapabilityProduct',
            new_name='ProductSecurityCapability',
        ),
    ]
