# Generated by Django 2.1.2 on 2018-10-15 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0017_auto_20181015_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSecurityRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(null=True, on_delete=models.SET(None), to='scorecard.Person')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=200)),
                ('function', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='productrole',
            name='person',
        ),
        migrations.RemoveField(
            model_name='productrole',
            name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='score',
            new_name='compliance_score',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='max_score',
            new_name='max_compliance_score',
        ),
        migrations.RemoveField(
            model_name='businessunit',
            name='percent_score',
        ),
        migrations.RemoveField(
            model_name='product',
            name='percent_score',
        ),
        migrations.AddField(
            model_name='businessunitgroup',
            name='max_score',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='businessunitgroup',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='max_people_score',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='max_process_score',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='max_technology_score',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='people_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='process_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='technology_score',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ProductRole',
        ),
        migrations.AddField(
            model_name='productsecurityrole',
            name='product',
            field=models.ForeignKey(null=True, on_delete=models.SET(None), to='scorecard.Product'),
        ),
        migrations.AddField(
            model_name='productsecurityrole',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scorecard.SecurityRole'),
        ),
    ]
