# Generated by Django 2.1.2 on 2018-10-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0018_auto_20181015_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='compliance_percent_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='max_total_score',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='people_percent_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='process_percent_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='technology_percent_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='total_percent_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
