# Generated by Django 2.1.2 on 2018-10-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0019_auto_20181015_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityrole',
            name='description',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='securityrole',
            name='function',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
