# Generated by Django 2.1.2 on 2018-10-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0021_auto_20181015_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityrole',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='securityrole',
            name='function',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
