# Generated by Django 2.1.2 on 2018-10-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0022_auto_20181015_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessunitgroup',
            name='max_score',
        ),
        migrations.RemoveField(
            model_name='businessunitgroup',
            name='score',
        ),
        migrations.AddField(
            model_name='businessunit',
            name='percent_score',
            field=models.FloatField(default=0),
        ),
    ]
