# Generated by Django 2.1.2 on 2018-10-18 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0023_auto_20181015_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='BUScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('max_score', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ProductScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('max_score', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='businessunit',
            name='max_score',
        ),
        migrations.RemoveField(
            model_name='businessunit',
            name='percent_score',
        ),
        migrations.RemoveField(
            model_name='businessunit',
            name='score',
        ),
        migrations.RemoveField(
            model_name='product',
            name='compliance_percent_score',
        ),
        migrations.RemoveField(
            model_name='product',
            name='compliance_score',
        ),
        migrations.RemoveField(
            model_name='product',
            name='max_compliance_score',
        ),
        migrations.RemoveField(
            model_name='product',
            name='max_people_score',
        ),
        migrations.RemoveField(
            model_name='product',
            name='max_process_score',
        ),
        migrations.RemoveField(
            model_name='product',
            name='max_technology_score',
        ),
        migrations.RemoveField(
            model_name='product',
            name='max_total_score',
        ),
        migrations.RemoveField(
            model_name='product',
            name='people_percent_score',
        ),
        migrations.RemoveField(
            model_name='product',
            name='people_score',
        ),
        migrations.RemoveField(
            model_name='product',
            name='process_percent_score',
        ),
        migrations.RemoveField(
            model_name='product',
            name='process_score',
        ),
        migrations.RemoveField(
            model_name='product',
            name='technology_percent_score',
        ),
        migrations.RemoveField(
            model_name='product',
            name='technology_score',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_percent_score',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_score',
        ),
        migrations.AddField(
            model_name='productscore',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scorecard.Product'),
        ),
        migrations.AddField(
            model_name='buscore',
            name='bu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scorecard.BusinessUnit'),
        ),
    ]
