# Generated by Django 2.1.2 on 2018-10-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0025_product_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SecuritySubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='securitycapability',
            name='details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='securitycapability',
            name='category',
            field=models.ForeignKey(null=True, on_delete=models.SET(''), to='scorecard.SecurityCategory'),
        ),
        migrations.AddField(
            model_name='securitycapability',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=models.SET(''), to='scorecard.SecuritySubCategory'),
        ),
    ]
