# Generated by Django 2.1.2 on 2018-10-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0027_auto_20181023_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productscore',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(''), to='scorecard.SecurityCategory'),
        ),
    ]
