# Generated by Django 2.1.2 on 2018-10-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0028_auto_20181023_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productscore',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
