# Generated by Django 2.1.2 on 2018-11-14 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0031_auto_20181107_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsecuritycapability',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scorecard.Status'),
        ),
    ]
