# Generated by Django 2.1.2 on 2018-11-15 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0032_auto_20181114_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='BUGroupScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, help_text='Integer Field')),
                ('max_score', models.IntegerField(default=1)),
                ('items_supported', models.IntegerField(default=0)),
                ('items_in_progress', models.IntegerField(default=0)),
                ('items_total', models.IntegerField(default=0)),
                ('bu_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scorecard.BusinessUnitGroup')),
            ],
        ),
    ]
